# このサイト全体のタイトル
site_name: 1日1回運命の出会いが必ず訪れるシンデレラ系アプリ

# meta description（og:description・twitter:descriptionでも使用）
description: 王子様からウィンクが届く！シンデレラ系という、新しいジャンルのマッチングサービス

# meta keywords
keywords: []

# カノニカル・og:urlなどで使われる、このサイトのURL
# （複数ページあるサイトでは、全てに同じURLを入れないように）
url: https://cinderella-castle.com

# Facebook OGP・Twitter cardsで使われる画像 フルURLで指定すること
ogp_image_url: /img/ogp.jpg
ogp_image_width: 1200
ogp_image_height: 630

# Facebookアプリのapp id（入れないとWarningが出る）
# facebook_app_id: 99999999999

# Twitter cardsの管理者として登録するアカウント（※任意）
# twitter_card_owner: '@TwitterJP'

# favicon
favicon_url: /img/favicon.png

# サイトをホーム画面に追加した際のアイコン画像
# webclipicon_url: http://example.com/webclipicon.png

# iOSにて、サイトをホーム画面に追加した際の、ステータスバーの挙動指定
# ios_status_bar: default
